### ISSUE TITLE
Exception in Tkinter callback

### ISSUE THREAD

**Issue by IanAdel** [JuliaPy/PyPlot.jl#330]
While using PyPlot.jl I am receiving the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/lib-tk/Tkinter.py", line 592, in callit
    func(*args)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/collections.py", line 321, in draw
    self._offset_position)
  File "/Users/ian/.julia/v0.6/Conda/deps/usr/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 120, in draw_path_collection
    return self._renderer.draw_path_collection(*kl, **kw)
TypeError: Cannot cast array data from dtype('S3') to dtype('float64') according to the rule 'safe'
PyObject Text(0.5,1,u'Massa')

**Comment by baggepinnen** [comment]
Same here under julia 1.0.3 and 
```
  [91a5bcdd] Plots v0.22.5
  [438e738f] PyCall v1.18.5
  [d330b81b] PyPlot v2.7.0
```

**Comment by japui-coder** [comment]
Exception in Tkinter callback #330
